apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-deployment
  template:
    metadata:
      labels:
        app: node-app-deployment
    spec:
      containers:
        - name: node-app
          image: yoavporag/node-app:latest
          ports:
          - containerPort: 3000
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"