apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  type: NodePort
  selector:
    app: node-app-deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000